name: Workflow

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Pushing Docker image to DockerHub
    runs-on: ubuntu-latest;macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Docker Hub Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: {{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest
          labels: ${{ steps.meta.outputs.labels }}
