
name: Workflow

on: [push]

env:
  DOCKER_REPO: marwaqureshi1

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
      - run: echo "post-checkout" && ls -lah && pwd
      - name: login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker buildx
        uses: docker/setup-buildx-action@v1
      - name: build push
        uses: docker/build-push-action@v2
        with:  
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest
